### PR TITLE
Switch to the team repo as the data source

### PR DESCRIPTION
**Pull request by emilyalbini**
This PR removes `mailmap.toml` and fetches the mailing lists from the [rust-lang/team](https://github.com/rust-lang/team) repository. We need to double-check the mailing lists generated by that repo before merging this.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Could you create a diff of what the mailmap would now look like?

**Comment by pietroalbini** [comment]
https://gist.github.com/pietroalbini/8601e7dc28966c6d654c1ee97e38c574/revisions

**Comment by Mark-Simulacrum** [comment]
That's a lot of changes! I think it might be more helpful to have a "people" diff, and by team vs. mailing list; regardless I think approving this is probably a matter of each team lead approving their own team's lists. Release team looks good...

**Comment by pietroalbini** [comment]
This is a cleaned up diff: https://gist.github.com/pietroalbini/6005d3aac5bbd6039706d671e00f2f4c

**Comment by steveklabnik** [comment]
Docs looks good.

**Comment by pietroalbini** [comment]
Continued on https://github.com/rust-lang/rust-central-station/pull/144.

**Pull request closed without merging**
